apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    argocd.argoproj.io/managed-by: argocd

---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    argocd.argoproj.io/managed-by: argocd