apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: osgo-test
  namespace: argocd
spec:
  destinations:
    - server: 'https://kubernetes.default.svc'
      namespace: '*'
  sourceRepos:
    - 'https://github.com/schj-z/osgo-test'
